[serve]
address = "0.0.0.0"
port = 8080
open = false
no_autoreload = false

[watch]
watch = [
    "./",
    "../../leptos_charts"
]

[[proxy]]
rewrite = "/api"
backend = "http://localhost:9090/api"
ws = false
